name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install OpenCL
        run: .\fetch-opencl-dev-win.cmd x64

      # - name: dir pf
      #   run: cd C:\"Program Files" && dir

      # - name: dir pf x86
      #   run: cd C:\"Program Files (x86)" && dir

      # - name: dir VS
      #   run: cd C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0" && dir
      
      # - name: dir VC
      #   run: cd C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\2022 && dir
      
      # - name: Set VS Path
      #   run:  C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat x64

      - name: Build
        id: build_script
        run: .\make.cmd
      
      - name: Test
        run: .\clinfo.exe

      - name: Upload artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          path: |
            clinfo.exe
